version: '3.8'

services:
  wms-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - wms-postgres
      - wms-redis
    networks:
      - wms-net
      - proxy-net

  wms-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:80"
    networks:
      - wms-net
      - proxy-net

  wms-postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: alaska
      POSTGRES_PASSWORD: alaska_pass
      POSTGRES_DB: wms
    networks:
      - wms-net

  wms-redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - wms-net

networks:
  wms-net:
    driver: bridge
  proxy-net:
    external: true

volumes:
  postgres-data:
  redis-data:
